# \u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 Gradle
gradleWrapperVersion=8.13

# \u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 \u0440\u0435\u043F\u043E\u0437\u0438\u0442\u043E\u0440\u0438\u0435\u0432
backstageNexusUrl=https://git.backstage-platform.ru/api/v4/projects/1/packages/maven
backstageNexusToken=gldt-xY7AP3gpEh9aY5p35XYg

# \u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 \u0441\u0431\u043E\u0440\u043A\u0438
sourceJavaVersion=17
sourceEncoding=UTF-8
appVersion=5.1.43

# \u041F\u043B\u0430\u0433\u0438\u043D\u044B
lombokVersion=8.12.1
sonarQubeVersion=6.0.1.5171
gradlePluginsVersion=2.0.18

# \u0417\u0430\u0432\u0438\u0441\u0438\u043C\u043E\u0441\u0442\u0438
springBootVersion=3.3.10
springCloudVersion=4.1.4
eclipseLinkVersion=4.0.5
jooqVersion=3.19.21
jbpmVersion=7.73.0.Final
camundaVersion=7.22.0
groovyVersion=4.0.26
nashornVersion=15.4
flywayVersion=11.4.1
flywayClickhouseVersion=10.17.0
hazelcastVersion=5.3.6
minioVersion=8.5.17
clickhouseJdbcVersion=0.8.2
postgresqlJdbcVersion=42.7.5
postgisVersion=2024.1.0
geolatteVersion=1.9.1
geojsonVersion=1.14
janinoVersion=3.1.12
feignJackson=13.3
springDocVersion=2.6.0
jerseyVersion=3.1.9
guavaVersion=33.4.5-jre
commonsIOVersion=2.18.0
commonsCodecVersion=1.18.0
commonsCSVVersion=1.14.0
commonsTextVersion=1.13.0
apachePOIVersion=5.4.0
kotlinVersion=1.8.10
tikaVersion=3.1.0

jupiterVersion=5.12.1
testContainersVersion=1.20.6

# \u041F\u0435\u0440\u0435\u043E\u043F\u0440\u0435\u0434\u0435\u043B\u0435\u043D\u0438\u0435 \u0442\u0440\u0430\u043D\u0437\u0438\u0442\u0438\u0432\u043D\u044B\u0445 \u0437\u0430\u0432\u0438\u0441\u0438\u043C\u043E\u0441\u0442\u0435\u0439 Spring Boot
flyway.version=${flywayVersion}
jooq.version=${jooqVersion}
postgresql.version=${postgresqlJdbcVersion}
hazelcast.version=${hazelcastVersion}
groovy.version=${groovyVersion}
kotlin.version=${kotlinVersion}
